### ISSUE TITLE
Bot replied with error message after succesfull backport

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/backportbot#423]
- Error: 
```js
Failed to create pull request: Validation Failed:
{
"resource":"PullRequest",
"code":"custom",
"message":"A pull request already exists for nextcloud-libraries:backport/5282/next."
}
```

- Reference: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5282

**Comment by skjnldsv** [comment]
You were too fast, you commented and merged, so the webhook got sent almost at the same time and the close triggered a backport and your comment triggered another one.
It's a tough race condition :see_no_evil:

**Comment by Antreesy** [comment]
Hm, I'm almost sure I left a comment after branch was merged and deleted. Is closing the PR suppose to trigger a backport, if it wasn't requested?

**Comment by skjnldsv** [comment]
You clicked merge and commented within a few seconds each.
- Merging will trigger the bot and parse all comments looking for a backport request (can take a few seconds)
- Commenting on a merged PR will also trigger a backport instantly
